version: '3'

services:
  backend-to-api:
    image: wizerd/pandora-to-api:latest
    restart: always
    ports:
      - "50011:33333"
    volumes:
      - ./log:/app/log
      - ./images:/app/images
      - ./data:/app/data
    